server:
  port: 8081

mysql:
  datasource:
    master:

      pool-name: master-pool
      jdbc-url: jdbc:mysql://localhost:3306/db_test?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      pool-name: slave-pool
      jdbc-url: jdbc:mysql://localhost:3306/db_test?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com:
      liyuan:
        demo:
          mapper: DEBUG
